# VLM-Anomaly — Full MVTec Sweep · Claude Opus 4.7

**Model:** `claude-opus-4-7`  
**Strategy:** 10 images per API call (batched) to maximise throughput  
**Free-tier Opus limits:** 50 RPM · 500K input TPM · 80K output TPM  

| Scope | Images | Est. cost |
|---|---|---|
| 1 category (smoke) | ~83 | ~$2.70 |
| Full sweep (15 cat) | ~1,245 | ~$26–32 |

> **$5 credit covers ~2 categories.** Add more credit before running the full sweep.

In [1]:
# ── Cell 1: Setup paths & sys.path ─────────────────────────────────────────
import sys
from pathlib import Path
from dotenv import load_dotenv

REPO_ROOT   = Path().resolve().parent
SRC_DIR     = REPO_ROOT / 'src'
PROMPTS_DIR = REPO_ROOT / 'prompts'
RESULTS_DIR = REPO_ROOT / 'results'
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

assert SRC_DIR.exists(),     f'src/ not found at {SRC_DIR}'
assert PROMPTS_DIR.exists(), f'prompts/ not found at {PROMPTS_DIR}'

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

load_dotenv(REPO_ROOT / '.env')

import vlm_anomaly
print(f'vlm_anomaly {vlm_anomaly.__version__} ready')
print(f'Results  : {RESULTS_DIR}')

vlm_anomaly 0.1.0 ready
Results  : /Users/sabareeswarans/Projects_26/VLM-Anomaly/results

In [2]:
# ── Cell 2: Verify API key ───────────────────────────────────────────────────
import os

api_key = os.environ.get('ANTHROPIC_API_KEY', '')
assert api_key, 'ANTHROPIC_API_KEY not set — add it to your .env file'
print(f'ANTHROPIC_API_KEY: {api_key[:12]}...{api_key[-4:]}')

ANTHROPIC_API_KEY: sk-ant-api03...SAAA

In [3]:
# ── Cell 3: Find MVTec dataset ──────────────────────────────────────────────
MVTEC_ROOT = None
for candidate in [
    REPO_ROOT / 'data' / 'mvtec',
    REPO_ROOT / 'data' / 'mvtec-ad',
    Path('/tmp/mvtec'),
]:
    if candidate.exists() and any(candidate.iterdir()):
        MVTEC_ROOT = candidate
        break

assert MVTEC_ROOT, f'MVTec not found. Expected at {REPO_ROOT}/data/mvtec'
categories = sorted([d.name for d in MVTEC_ROOT.iterdir() if d.is_dir()])
print(f'MVTec root : {MVTEC_ROOT}')
print(f'Categories : {len(categories)} → {categories}')

MVTec root : /Users/sabareeswarans/Projects_26/VLM-Anomaly/data/mvtec
Categories : 15 → ['bottle', 'cable', 'capsule', 'carpet', 'grid', 'hazelnut', 'leather', 'metal_nut', 'pill', 'screw', 'tile', 'toothbrush', 'transistor', 'wood', 'zipper']

In [4]:
# ── Cell 4: Configure ───────────────────────────────────────────────────────
MODEL      = 'claude-opus-4-7'
PROMPT_KEY = 'manufacturing.detailed'
BATCH_SIZE = 10      # images per API call — max 20, 10 is reliable
BUDGET_USD = 5.0     # hard cap — raise after adding more credit

est_images = len(categories) * 83
est_cost   = est_images * 0.028   # ~$28 / 1M input tokens for Opus
print(f'Model        : {MODEL}')
print(f'Batch size   : {BATCH_SIZE} images/call')
print(f'Budget cap   : ${BUDGET_USD}  ← raise this when adding more credit')
print(f'Est. images  : ~{est_images}')
print(f'Est. cost    : ~${est_cost:.2f} full sweep')
print(f'  $5 covers  : ~{int(5 / (est_cost / est_images))} images (~{int(5 / (est_cost / est_images) / 83)} categories)')

Model        : claude-opus-4-7
Batch size   : 10 images/call
Budget cap   : $5.0  ← raise this when adding more credit
Est. images  : ~1245
Est. cost    : ~$34.86 full sweep
  $5 covers  : ~178 images (~2 categories)

In [5]:
# ── Cell 5: SMOKE TEST — 1 image, verify API before full sweep ──────────────
# (backend is built in Cell 6 — run that first, then optionally run this smoke test)

smoke_img = next((MVTEC_ROOT / 'bottle' / 'test').rglob('*.png'))
print(f'Smoke test image: {smoke_img.relative_to(REPO_ROOT)}')

smoke_result = backend.predict(
    smoke_img,
    'Is there any defect or anomaly? Reply with JSON only: '
    '{"is_anomalous": bool, "confidence": float, "defect_type": str, "description": str}'
)

print(f'  is_anomalous : {smoke_result.is_anomalous}')
print(f'  confidence   : {smoke_result.confidence:.2f}')
print(f'  defect_type  : {smoke_result.defect_type}')
print(f'  description  : {smoke_result.description[:100]}')
print(f'  latency_ms   : {smoke_result.latency_ms:.0f}')
print(f'  cost_usd     : ${smoke_result.cost_usd:.6f}')
print(f'  tokens_in    : {smoke_result.tokens_in}')
print(f'  tokens_out   : {smoke_result.tokens_out}')
print(f'  parse_error  : {smoke_result.parse_error}')
print()
print('✓ Smoke test passed — API key and model are working.')

Smoke test image: data/mvtec/bottle/test/broken_small/002.png

2026-05-24T02:38:32.532057Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T02:38:32.535246Z [info     ] anthropic.predict              [vlm_anomaly.backends.anthropic_backend] confidence=0.95 cost_usd=0.02425 image=002.png is_anomalous=True latency_ms=2994 model=claude-opus-4-7 parse_error=False tokens_in=1157 tokens_out=92

  is_anomalous : True
  confidence   : 0.95
  defect_type  : chip/contamination on rim
  description  : A visible chip or glass damage with residue is present on the right side of the bottle's inner rim,
  latency_ms   : 2994
  cost_usd     : $0.024255
  tokens_in    : 1157
  tokens_out   : 92
  parse_error  : False

✓ Smoke test passed — API key and model are working.

In [5]:
# ── Cell 6: Build shared objects ────────────────────────────────────────────
from vlm_anomaly.backends.anthropic_backend import AnthropicBackend
from vlm_anomaly.config import Settings
from vlm_anomaly.datasets.mvtec import MVTec
from vlm_anomaly.evaluators.prompt_library import PromptLibrary
from vlm_anomaly.logging import configure_logging

configure_logging(log_level='INFO')
backend = AnthropicBackend(model=MODEL)

settings = Settings(
    _env_file=str(REPO_ROOT / '.env'),
    data_dir=str(MVTEC_ROOT.parent),
    results_dir=str(RESULTS_DIR),
    default_budget_usd=BUDGET_USD,
)
settings.results_dir = RESULTS_DIR

dataset    = MVTec(root_dir=MVTEC_ROOT)
prompt_lib = PromptLibrary(prompts_dir=PROMPTS_DIR)
prompt_str = prompt_lib.render(PROMPT_KEY)

print(f'Dataset  : {MVTEC_ROOT}')
print(f'Backend  : {backend.name} / {MODEL}')
print(f'Prompt   : {PROMPT_KEY} ({len(prompt_str)} chars)')

Dataset  : /Users/sabareeswarans/Projects_26/VLM-Anomaly/data/mvtec
Backend  : anthropic / claude-opus-4-7
Prompt   : manufacturing.detailed (587 chars)

In [6]:
# ── Cell 7: Run all categories (batched, idempotent, resumable) ─────────────
import json
import uuid as _uuid
from datetime import timezone, datetime
from tqdm.auto import tqdm
from sklearn.metrics import roc_auc_score, f1_score
from vlm_anomaly.logging import configure_logging

configure_logging(log_level='INFO')

MODEL_ID     = f'anthropic/{MODEL}'
total_cost   = 0.0
all_category_results = []


def _find_existing(results_dir, category, model_id):
    """Return (file, n_done) for a matching partial or complete run, else (None, 0)."""
    for f in results_dir.glob(f'*_mvtec_{category}.jsonl'):
        if f.stat().st_size < 10:
            continue
        try:
            lines = [l for l in f.read_text().splitlines() if l.strip()]
            if not lines:
                continue
            rec = json.loads(lines[0])
            if rec.get('model_id') == model_id:
                return f, len(lines)
        except Exception:
            pass
    return None, 0


for category in tqdm(categories, desc='MVTec categories'):
    all_samples = dataset.samples(category, split='test')
    total       = len(all_samples)

    existing_file, n_done = _find_existing(RESULTS_DIR, category, MODEL_ID)

    if n_done >= total:
        print(f'  [skip]   {category} — complete ({n_done}/{total})')
        continue
    elif n_done > 0:
        print(f'  [resume] {category} — continuing from image {n_done}/{total}')
        out_file       = existing_file
        samples_to_run = all_samples[n_done:]
    else:
        experiment_id  = _uuid.uuid4().hex[:8]
        out_file       = RESULTS_DIR / f'{experiment_id}_mvtec_{category}.jsonl'
        samples_to_run = all_samples

    images = [s.image_path for s in samples_to_run]
    labels = [s.label      for s in samples_to_run]
    rows   = []
    cat_cost = 0.0

    for i in tqdm(range(0, len(images), BATCH_SIZE), desc=category, leave=False):
        batch_imgs = images[i : i + BATCH_SIZE]
        results    = backend.predict_batch(batch_imgs, prompt_str)

        for pred, label in zip(results, labels[i : i + BATCH_SIZE]):
            row = {
                'experiment_id': out_file.stem.split('_')[0],
                'model_id':       MODEL_ID,
                'backend':        'anthropic',
                'dataset':        'mvtec',
                'category':       category,
                'sample_label':   label,
                'prediction': {
                    'image_path':   str(pred.image_path),
                    'is_anomalous': pred.is_anomalous,
                    'confidence':   pred.confidence,
                    'description':  pred.description,
                    'defect_type':  pred.defect_type,
                    'regions':      pred.regions,
                    'raw_response': pred.raw_response,
                    'latency_ms':   pred.latency_ms,
                    'cost_usd':     pred.cost_usd,
                    'tokens_in':    pred.tokens_in,
                    'tokens_out':   pred.tokens_out,
                    'parse_error':  pred.parse_error,
                },
                'timestamp': datetime.now(timezone.utc).isoformat(),
            }
            rows.append(row)
            with out_file.open('a') as fh:
                fh.write(json.dumps(row) + '\n')

        cat_cost += sum(r.cost_usd for r in results)

    if not rows:
        continue

    # Compute metrics over ALL rows in the file (including any resumed portion)
    all_lines = [json.loads(l) for l in out_file.read_text().splitlines() if l.strip()]
    gt     = [r['sample_label']               for r in all_lines]
    scores = [r['prediction']['confidence'] if r['prediction']['is_anomalous']
              else 1 - r['prediction']['confidence'] for r in all_lines]
    preds  = [int(r['prediction']['is_anomalous']) for r in all_lines]
    try:
        auroc = roc_auc_score(gt, scores)
    except Exception:
        auroc = float('nan')
    f1 = f1_score(gt, preds, zero_division=0)

    total_cost += cat_cost
    all_category_results.append({
        'category': category, 'auroc': auroc, 'f1': f1,
        'n': len(all_lines), 'cost': cat_cost,
    })
    print(f'  {category:12s}  AUROC={auroc:.3f}  F1={f1:.3f}  '
          f'n={len(all_lines)}  cost=${cat_cost:.4f}')

print(f'\nDone. Total cost this run: ${total_cost:.4f}')

MVTec categories:   0%|          | 0/15 [00:00<?, ?it/s]

  [skip]   bottle — complete (83/83)
  [resume] cable — continuing from image 130/150

cable:   0%|          | 0/2 [00:00<?, ?it/s]

2026-05-24T03:26:29.378850Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:26:29.382595Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.26447 latency_ms=11830 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=744
2026-05-24T03:26:29.383366Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:26:29.384047Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:26:29.385021Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:26:29.385707Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:26:29.386705Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:26:29.387497Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:26:29.388617Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:26:29.389640Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:26:29.390516Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:26:29.391414Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:26:40.699591Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:26:40.702860Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25951 latency_ms=11288 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=678
2026-05-24T03:26:40.703585Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:26:40.704244Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:26:40.705403Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:26:40.706318Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:26:40.707321Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:26:40.708030Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:26:40.708973Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:26:40.709680Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:26:40.710572Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:26:40.711265Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=009.png is_anomalous=True parse_error=False

  cable         AUROC=0.940  F1=0.857  n=150  cost=$0.5240

capsule:   0%|          | 0/14 [00:00<?, ?it/s]

2026-05-24T03:26:50.709017Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:26:50.712241Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.24189 latency_ms=9936 model=claude-opus-4-7 parse_errors=0 tokens_in=13181 tokens_out=589
2026-05-24T03:26:50.713016Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:26:50.713739Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.98 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:26:50.714758Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:26:50.715632Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:26:50.717091Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:26:50.718326Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:26:50.719877Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:26:50.721919Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:26:50.724275Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:26:50.725644Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:27:05.497829Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:27:05.501048Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.24324 latency_ms=14755 model=claude-opus-4-7 parse_errors=0 tokens_in=13181 tokens_out=607
2026-05-24T03:27:05.501867Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:27:05.502631Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:27:05.503529Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=012.png is_anomalous=False parse_error=False
2026-05-24T03:27:05.504160Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=013.png is_anomalous=False parse_error=False
2026-05-24T03:27:05.504972Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:27:05.505611Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:27:05.506496Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=016.png is_anomalous=False parse_error=False
2026-05-24T03:27:05.507520Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:27:05.508993Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:27:05.510119Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=019.png is_anomalous=True parse_error=False
2026-05-24T03:27:16.440353Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:27:16.443615Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.24707 latency_ms=10920 model=claude-opus-4-7 parse_errors=0 tokens_in=13181 tokens_out=658
2026-05-24T03:27:16.444285Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=020.png is_anomalous=True parse_error=False
2026-05-24T03:27:16.444932Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=021.png is_anomalous=False parse_error=False
2026-05-24T03:27:16.445778Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=022.png is_anomalous=True parse_error=False
2026-05-24T03:27:16.446595Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:27:16.447633Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:27:16.448378Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:27:16.449393Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:27:16.450158Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:27:16.451275Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:27:16.452009Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:27:27.417850Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:27:27.420983Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.24391 latency_ms=10956 model=claude-opus-4-7 parse_errors=0 tokens_in=13181 tokens_out=616
2026-05-24T03:27:27.421671Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:27:27.422461Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:27:27.423597Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=009.png is_anomalous=False parse_error=False
2026-05-24T03:27:27.424244Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:27:27.425141Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=011.png is_anomalous=False parse_error=False
2026-05-24T03:27:27.425829Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:27:27.426637Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:27:27.427286Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:27:27.428248Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:27:27.429035Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:27:39.178066Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:27:39.181323Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.24069 latency_ms=11740 model=claude-opus-4-7 parse_errors=0 tokens_in=13181 tokens_out=573
2026-05-24T03:27:39.182171Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:27:39.182874Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=018.png is_anomalous=False parse_error=False
2026-05-24T03:27:39.183602Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=019.png is_anomalous=True parse_error=False
2026-05-24T03:27:39.184233Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=020.png is_anomalous=True parse_error=False
2026-05-24T03:27:39.185066Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=021.png is_anomalous=True parse_error=False
2026-05-24T03:27:39.185705Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:27:39.186673Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=001.png is_anomalous=False parse_error=False
2026-05-24T03:27:39.187328Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:27:39.188386Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=003.png is_anomalous=False parse_error=False
2026-05-24T03:27:39.189143Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=004.png is_anomalous=False parse_error=False
2026-05-24T03:27:48.308414Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:27:48.311578Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.24152 latency_ms=9048 model=claude-opus-4-7 parse_errors=0 tokens_in=13181 tokens_out=584
2026-05-24T03:27:48.312266Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:27:48.312862Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=006.png is_anomalous=False parse_error=False
2026-05-24T03:27:48.313583Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=007.png is_anomalous=False parse_error=False
2026-05-24T03:27:48.314425Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:27:48.315067Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:27:48.315899Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:27:48.316495Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:27:48.317343Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=012.png is_anomalous=False parse_error=False
2026-05-24T03:27:48.317936Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:27:48.318742Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=014.png is_anomalous=False parse_error=False
2026-05-24T03:27:57.729871Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:27:57.733016Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.24421 latency_ms=9404 model=claude-opus-4-7 parse_errors=0 tokens_in=13181 tokens_out=620
2026-05-24T03:27:57.733789Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:27:57.734426Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:27:57.735255Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:27:57.735853Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:27:57.736712Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=019.png is_anomalous=False parse_error=False
2026-05-24T03:27:57.737380Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=020.png is_anomalous=False parse_error=False
2026-05-24T03:27:57.738187Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=021.png is_anomalous=False parse_error=False
2026-05-24T03:27:57.738781Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=022.png is_anomalous=False parse_error=False
2026-05-24T03:27:57.739575Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:27:57.740215Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:28:10.417205Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:28:10.420457Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.24227 latency_ms=12671 model=claude-opus-4-7 parse_errors=0 tokens_in=13181 tokens_out=594
2026-05-24T03:28:10.421130Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:28:10.421718Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:28:10.422258Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:28:10.423155Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:28:10.423788Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:28:10.424613Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=007.png is_anomalous=False parse_error=False
2026-05-24T03:28:10.425271Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:28:10.433180Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:28:10.434328Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:28:10.435257Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:28:21.152529Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:28:21.155595Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.24451 latency_ms=10710 model=claude-opus-4-7 parse_errors=0 tokens_in=13181 tokens_out=624
2026-05-24T03:28:21.156262Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:28:21.156913Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:28:21.157736Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:28:21.158480Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:28:21.159317Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.6 image=016.png is_anomalous=False parse_error=False
2026-05-24T03:28:21.159954Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.65 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:28:21.160876Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:28:21.161487Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=019.png is_anomalous=True parse_error=False
2026-05-24T03:28:21.162315Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=020.png is_anomalous=True parse_error=False
2026-05-24T03:28:21.162925Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.55 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:28:31.282139Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:28:31.285181Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.24241 latency_ms=10113 model=claude-opus-4-7 parse_errors=0 tokens_in=13181 tokens_out=596
2026-05-24T03:28:31.285835Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:28:31.286471Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=002.png is_anomalous=False parse_error=False

  capsule       AUROC=0.654  F1=0.818  n=132  cost=$3.2050

carpet:   0%|          | 0/12 [00:00<?, ?it/s]

2026-05-24T03:29:14.987292Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:29:14.990460Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25396 latency_ms=10470 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=604
2026-05-24T03:29:14.991108Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:29:14.991742Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:29:14.992382Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:29:14.993283Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:29:14.993908Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.65 image=004.png is_anomalous=False parse_error=False
2026-05-24T03:29:14.994761Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:29:14.995345Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:29:14.996101Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:29:14.996758Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:29:14.997607Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:29:27.553919Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:29:27.557825Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25606 latency_ms=12549 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=632
2026-05-24T03:29:27.558562Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:29:27.559212Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:29:27.560082Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:29:27.560708Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:29:27.561560Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:29:27.562200Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:29:27.562978Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:29:27.563592Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:29:27.564398Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:29:27.565021Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:29:38.911665Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:29:38.916050Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25899 latency_ms=11341 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=671
2026-05-24T03:29:38.916774Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:29:38.917420Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:29:38.918289Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:29:38.918927Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:29:38.919794Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:29:38.930175Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:29:38.931100Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:29:38.931823Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:29:38.932675Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:29:38.933319Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:29:49.611413Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:29:49.614592Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25404 latency_ms=10671 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=605
2026-05-24T03:29:49.615262Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:29:49.615934Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:29:49.616804Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:29:49.617436Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:29:49.618289Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:29:49.618925Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:29:49.619729Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:29:49.620377Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=001.png is_anomalous=False parse_error=False
2026-05-24T03:29:49.621186Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:29:49.621811Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.87 image=003.png is_anomalous=False parse_error=False
2026-05-24T03:29:58.828954Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:29:58.831862Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.24864 latency_ms=9200 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=533
2026-05-24T03:29:58.832520Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=004.png is_anomalous=False parse_error=False
2026-05-24T03:29:58.833216Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=005.png is_anomalous=False parse_error=False
2026-05-24T03:29:58.834065Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.87 image=006.png is_anomalous=False parse_error=False
2026-05-24T03:29:58.834691Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.89 image=007.png is_anomalous=False parse_error=False
2026-05-24T03:29:58.835543Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=008.png is_anomalous=False parse_error=False
2026-05-24T03:29:58.836178Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.87 image=009.png is_anomalous=False parse_error=False
2026-05-24T03:29:58.837019Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.86 image=010.png is_anomalous=False parse_error=False
2026-05-24T03:29:58.837643Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=011.png is_anomalous=False parse_error=False
2026-05-24T03:29:58.838461Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.89 image=012.png is_anomalous=False parse_error=False
2026-05-24T03:29:58.839057Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=013.png is_anomalous=False parse_error=False
2026-05-24T03:30:08.658905Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:30:08.662193Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.24999 latency_ms=9813 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=551
2026-05-24T03:30:08.662962Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=014.png is_anomalous=False parse_error=False
2026-05-24T03:30:08.663863Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=015.png is_anomalous=False parse_error=False
2026-05-24T03:30:08.664817Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=016.png is_anomalous=False parse_error=False
2026-05-24T03:30:08.665460Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.91 image=017.png is_anomalous=False parse_error=False
2026-05-24T03:30:08.666246Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=018.png is_anomalous=False parse_error=False
2026-05-24T03:30:08.666883Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=019.png is_anomalous=False parse_error=False
2026-05-24T03:30:08.667687Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=020.png is_anomalous=False parse_error=False
2026-05-24T03:30:08.668363Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.6 image=021.png is_anomalous=True parse_error=False
2026-05-24T03:30:08.669182Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=022.png is_anomalous=False parse_error=False
2026-05-24T03:30:08.669814Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=023.png is_anomalous=False parse_error=False
2026-05-24T03:30:19.844985Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:30:19.848970Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25509 latency_ms=11167 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=619
2026-05-24T03:30:19.849734Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=024.png is_anomalous=True parse_error=False
2026-05-24T03:30:19.850404Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=025.png is_anomalous=True parse_error=False
2026-05-24T03:30:19.851997Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=026.png is_anomalous=False parse_error=False
2026-05-24T03:30:19.852906Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=027.png is_anomalous=False parse_error=False
2026-05-24T03:30:19.853565Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:30:19.854434Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.6 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:30:19.855119Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:30:19.856025Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:30:19.856697Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:30:19.857602Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:30:30.367061Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:30:30.370003Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25149 latency_ms=10498 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=571
2026-05-24T03:30:30.370689Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:30:30.371310Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:30:30.371932Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:30:30.372561Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:30:30.373167Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:30:30.374018Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:30:30.374694Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:30:30.375559Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:30:30.376255Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:30:30.377099Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:30:41.734949Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:30:41.737914Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25599 latency_ms=11349 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=631
2026-05-24T03:30:41.738590Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:30:41.739249Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:30:41.740091Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:30:41.740835Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:30:41.741653Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:30:41.742327Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:30:41.743148Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:30:41.743955Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:30:41.745028Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:30:41.745928Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:30:52.588129Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:30:52.591281Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25449 latency_ms=10835 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=611
2026-05-24T03:30:52.592111Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:30:52.592948Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=010.png is_anomalous=True parse_error=False

  carpet        AUROC=0.996  F1=0.972  n=117  cost=$2.9743

grid:   0%|          | 0/8 [00:00<?, ?it/s]

2026-05-24T03:31:22.901318Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:31:22.904440Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25711 latency_ms=10695 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=646
2026-05-24T03:31:22.905188Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:31:22.905855Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:31:22.906735Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:31:22.907468Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:31:22.909086Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:31:22.909875Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:31:22.910643Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:31:22.911901Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:31:22.912999Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:31:22.913652Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:31:33.104566Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:31:33.107916Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25629 latency_ms=10183 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=635
2026-05-24T03:31:33.108611Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:31:33.109334Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:31:33.110462Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:31:33.111127Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:31:33.112075Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:31:33.113061Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:31:33.114403Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:31:33.115458Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.91 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:31:33.116104Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:31:33.116931Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:31:43.382241Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:31:43.385419Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25532 latency_ms=10258 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=622
2026-05-24T03:31:43.386100Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:31:43.386761Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:31:43.387669Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:31:43.388287Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:31:43.389115Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:31:43.389769Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:31:43.390558Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:31:43.391201Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:31:43.391978Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:31:43.392586Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:31:54.599646Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:31:54.604885Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25629 latency_ms=11202 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=635
2026-05-24T03:31:54.605898Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:31:54.606829Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:31:54.607879Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=008.png is_anomalous=False parse_error=False
2026-05-24T03:31:54.608863Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:31:54.610055Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:31:54.611090Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:31:54.612236Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=001.png is_anomalous=False parse_error=False
2026-05-24T03:31:54.613851Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.5 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:31:54.615591Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=003.png is_anomalous=False parse_error=False
2026-05-24T03:31:54.617430Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=004.png is_anomalous=False parse_error=False
2026-05-24T03:32:04.473409Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:32:04.476581Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25141 latency_ms=9846 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=570
2026-05-24T03:32:04.477235Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=005.png is_anomalous=False parse_error=False
2026-05-24T03:32:04.478022Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=006.png is_anomalous=False parse_error=False
2026-05-24T03:32:04.478907Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.86 image=007.png is_anomalous=False parse_error=False
2026-05-24T03:32:04.479613Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.84 image=008.png is_anomalous=False parse_error=False
2026-05-24T03:32:04.480574Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=009.png is_anomalous=False parse_error=False
2026-05-24T03:32:04.481286Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.87 image=010.png is_anomalous=False parse_error=False
2026-05-24T03:32:04.482120Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.86 image=011.png is_anomalous=False parse_error=False
2026-05-24T03:32:04.482756Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=012.png is_anomalous=False parse_error=False
2026-05-24T03:32:04.483512Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.84 image=013.png is_anomalous=False parse_error=False
2026-05-24T03:32:04.484130Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.86 image=014.png is_anomalous=False parse_error=False
2026-05-24T03:32:15.428370Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:32:15.431967Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25337 latency_ms=10938 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=596
2026-05-24T03:32:15.432835Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=015.png is_anomalous=False parse_error=False
2026-05-24T03:32:15.433615Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=016.png is_anomalous=False parse_error=False
2026-05-24T03:32:15.434536Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=017.png is_anomalous=False parse_error=False
2026-05-24T03:32:15.435219Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=018.png is_anomalous=False parse_error=False
2026-05-24T03:32:15.436150Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=019.png is_anomalous=False parse_error=False
2026-05-24T03:32:15.436814Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=020.png is_anomalous=False parse_error=False
2026-05-24T03:32:15.437751Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:32:15.438441Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:32:15.439356Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:32:15.440063Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:32:28.437360Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:32:28.440397Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25839 latency_ms=12989 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=663
2026-05-24T03:32:28.441197Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:32:28.441928Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:32:28.442876Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:32:28.443547Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:32:28.444458Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:32:28.445165Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:32:28.446088Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:32:28.446827Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:32:28.447688Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:32:28.448347Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:32:37.482111Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:32:37.485195Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=8 cost_usd=0.20503 latency_ms=9026 model=claude-opus-4-7 parse_errors=0 tokens_in=11159 tokens_out=502
2026-05-24T03:32:37.485885Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:32:37.486532Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:32:37.487407Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:32:37.488033Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:32:37.488966Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:32:37.489598Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:32:37.490436Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:32:37.491057Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=010.png is_anomalous=True parse_error=False

  grid          AUROC=0.994  F1=0.982  n=78  cost=$1.9932

hazelnut:   0%|          | 0/11 [00:00<?, ?it/s]

2026-05-24T03:32:47.586066Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:32:47.589549Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25419 latency_ms=10031 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=607
2026-05-24T03:32:47.590256Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.98 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:32:47.590852Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:32:47.591491Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:32:47.592144Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:32:47.592715Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:32:47.593585Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:32:47.594214Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:32:47.595156Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.98 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:32:47.595924Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:32:47.596834Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:32:58.046208Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:32:58.050254Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25524 latency_ms=10443 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=621
2026-05-24T03:32:58.050918Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.98 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:32:58.051566Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:32:58.052327Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:32:58.053034Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:32:58.054056Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:32:58.054688Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:32:58.055587Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:32:58.056244Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:32:58.057278Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:32:58.058026Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:33:08.677061Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:33:08.680990Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25419 latency_ms=10606 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=607
2026-05-24T03:33:08.681805Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:33:08.682423Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:33:08.683267Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:33:08.683923Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:33:08.684817Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:33:08.685457Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:33:08.686251Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:33:08.686904Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:33:08.687713Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:33:08.688363Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:33:18.508637Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:33:18.511857Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25209 latency_ms=9812 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=579
2026-05-24T03:33:18.512615Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:33:18.513319Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:33:18.514302Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:33:18.514990Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:33:18.515887Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:33:18.516516Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:33:18.517321Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=001.png is_anomalous=False parse_error=False
2026-05-24T03:33:18.517966Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:33:18.519012Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=003.png is_anomalous=False parse_error=False
2026-05-24T03:33:18.519885Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=004.png is_anomalous=False parse_error=False
2026-05-24T03:33:30.184043Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:33:30.187057Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25359 latency_ms=11656 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=599
2026-05-24T03:33:30.187803Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=005.png is_anomalous=False parse_error=False
2026-05-24T03:33:30.188436Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=006.png is_anomalous=False parse_error=False
2026-05-24T03:33:30.189371Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.83 image=007.png is_anomalous=False parse_error=False
2026-05-24T03:33:30.190018Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:33:30.190892Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.84 image=009.png is_anomalous=False parse_error=False
2026-05-24T03:33:30.191551Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.65 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:33:30.192387Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=011.png is_anomalous=False parse_error=False
2026-05-24T03:33:30.193042Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.6 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:33:30.193897Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=013.png is_anomalous=False parse_error=False
2026-05-24T03:33:30.194595Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=014.png is_anomalous=False parse_error=False
2026-05-24T03:33:40.118544Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:33:40.121613Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25449 latency_ms=9914 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=611
2026-05-24T03:33:40.122290Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=015.png is_anomalous=False parse_error=False
2026-05-24T03:33:40.122894Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=016.png is_anomalous=False parse_error=False
2026-05-24T03:33:40.123494Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=017.png is_anomalous=False parse_error=False
2026-05-24T03:33:40.124396Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=018.png is_anomalous=False parse_error=False
2026-05-24T03:33:40.125029Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=019.png is_anomalous=False parse_error=False
2026-05-24T03:33:40.125899Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=020.png is_anomalous=False parse_error=False
2026-05-24T03:33:40.126549Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=021.png is_anomalous=False parse_error=False
2026-05-24T03:33:40.127329Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=022.png is_anomalous=False parse_error=False
2026-05-24T03:33:40.127959Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=023.png is_anomalous=False parse_error=False
2026-05-24T03:33:40.128804Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=024.png is_anomalous=False parse_error=False
2026-05-24T03:33:51.588655Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:33:51.592700Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25682 latency_ms=11453 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=642
2026-05-24T03:33:51.593389Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=025.png is_anomalous=False parse_error=False
2026-05-24T03:33:51.594052Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=026.png is_anomalous=False parse_error=False
2026-05-24T03:33:51.594908Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=027.png is_anomalous=True parse_error=False
2026-05-24T03:33:51.595556Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=028.png is_anomalous=True parse_error=False
2026-05-24T03:33:51.597224Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=029.png is_anomalous=False parse_error=False
2026-05-24T03:33:51.598039Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=030.png is_anomalous=False parse_error=False
2026-05-24T03:33:51.598628Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.65 image=031.png is_anomalous=True parse_error=False
2026-05-24T03:33:51.599413Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=032.png is_anomalous=True parse_error=False
2026-05-24T03:33:51.600036Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.6 image=033.png is_anomalous=True parse_error=False
2026-05-24T03:33:51.600864Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=034.png is_anomalous=False parse_error=False
2026-05-24T03:34:01.524547Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:34:01.528425Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25254 latency_ms=9915 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=585
2026-05-24T03:34:01.529109Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=035.png is_anomalous=False parse_error=False
2026-05-24T03:34:01.529770Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=036.png is_anomalous=True parse_error=False
2026-05-24T03:34:01.530746Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=037.png is_anomalous=False parse_error=False
2026-05-24T03:34:01.531393Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=038.png is_anomalous=False parse_error=False
2026-05-24T03:34:01.532268Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=039.png is_anomalous=False parse_error=False
2026-05-24T03:34:01.532880Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:34:01.533710Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:34:01.534330Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:34:01.535168Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:34:01.535800Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:34:11.233236Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:34:11.238760Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25201 latency_ms=9693 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=578
2026-05-24T03:34:11.239956Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:34:11.240967Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:34:11.241907Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=007.png is_anomalous=False parse_error=False
2026-05-24T03:34:11.242539Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:34:11.243478Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:34:11.244106Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:34:11.244959Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:34:11.245611Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:34:11.246520Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:34:11.247146Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:34:20.647512Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:34:20.650817Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25119 latency_ms=9394 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=567
2026-05-24T03:34:20.651597Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:34:20.652215Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=016.png is_anomalous=True parse_error=False

  hazelnut      AUROC=0.891  F1=0.832  n=110  cost=$2.7966

leather:   0%|          | 0/13 [00:00<?, ?it/s]

2026-05-24T03:34:42.703526Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:34:42.708405Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.24909 latency_ms=9772 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=539
2026-05-24T03:34:42.709168Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:34:42.710056Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:34:42.711120Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:34:42.712028Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:34:42.714427Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:34:42.715790Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:34:42.716847Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:34:42.718074Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:34:42.719850Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:34:42.721695Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:34:51.939407Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:34:51.942437Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.24834 latency_ms=9204 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=529
2026-05-24T03:34:51.943081Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:34:51.943758Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:34:51.944646Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:34:51.945265Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:34:51.946093Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:34:51.946715Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:34:51.947369Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:34:51.948045Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:34:51.948845Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:34:51.949510Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:35:01.732784Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:35:01.736414Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25149 latency_ms=9776 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=571
2026-05-24T03:35:01.737099Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:35:01.737725Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:35:01.738319Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:35:01.739326Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:35:01.739996Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:35:01.740822Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:35:01.741508Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:35:01.743037Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:35:01.743828Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:35:01.744426Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:35:12.079525Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:35:12.083033Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25554 latency_ms=10328 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=625
2026-05-24T03:35:12.083818Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:35:12.084514Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:35:12.085347Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:35:12.085968Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:35:12.086834Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:35:12.087432Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:35:12.096417Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:35:12.097198Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:35:12.098230Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:35:12.098924Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:35:21.591112Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:35:21.595908Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25104 latency_ms=9486 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=565
2026-05-24T03:35:21.596625Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:35:21.597220Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:35:21.597869Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:35:21.598886Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:35:21.599706Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:35:21.600769Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:35:21.601460Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:35:21.602331Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:35:21.603039Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:35:21.603984Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:35:31.125501Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:35:31.130168Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25254 latency_ms=9515 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=585
2026-05-24T03:35:31.131808Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:35:31.134386Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:35:31.136148Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:35:31.136922Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:35:31.138025Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:35:31.140210Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:35:31.142143Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:35:31.144376Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:35:31.145597Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:35:31.146323Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:35:41.358556Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:35:41.361612Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25239 latency_ms=10204 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=583
2026-05-24T03:35:41.362277Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:35:41.362910Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:35:41.363500Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:35:41.364416Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:35:41.365255Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:35:41.366138Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:35:41.366902Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:35:41.369264Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:35:41.370234Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:35:41.371089Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:35:51.605586Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:35:51.609104Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.24984 latency_ms=10227 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=549
2026-05-24T03:35:51.609819Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:35:51.610641Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:35:51.612033Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:35:51.612924Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:35:51.613731Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:35:51.614656Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=001.png is_anomalous=False parse_error=False
2026-05-24T03:35:51.615458Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:35:51.616430Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=003.png is_anomalous=False parse_error=False
2026-05-24T03:35:51.617269Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=004.png is_anomalous=False parse_error=False
2026-05-24T03:35:51.618317Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=005.png is_anomalous=False parse_error=False
2026-05-24T03:36:00.706815Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:36:00.710814Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.24932 latency_ms=9077 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=542
2026-05-24T03:36:00.711447Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=006.png is_anomalous=False parse_error=False
2026-05-24T03:36:00.712061Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=007.png is_anomalous=False parse_error=False
2026-05-24T03:36:00.712676Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=008.png is_anomalous=False parse_error=False
2026-05-24T03:36:00.713560Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=009.png is_anomalous=False parse_error=False
2026-05-24T03:36:00.714263Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.89 image=010.png is_anomalous=False parse_error=False
2026-05-24T03:36:00.715094Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=011.png is_anomalous=False parse_error=False
2026-05-24T03:36:00.715986Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=012.png is_anomalous=False parse_error=False
2026-05-24T03:36:00.716985Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=013.png is_anomalous=False parse_error=False
2026-05-24T03:36:00.717637Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=014.png is_anomalous=False parse_error=False
2026-05-24T03:36:00.718553Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=015.png is_anomalous=False parse_error=False
2026-05-24T03:36:09.928807Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:36:09.932308Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.24917 latency_ms=9202 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=540
2026-05-24T03:36:09.933056Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=016.png is_anomalous=False parse_error=False
2026-05-24T03:36:09.933725Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=017.png is_anomalous=False parse_error=False

  leather       AUROC=1.000  F1=0.995  n=124  cost=$3.1195

metal_nut:   0%|          | 0/12 [00:00<?, ?it/s]

2026-05-24T03:36:45.902273Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:36:45.905945Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.14236 latency_ms=9893 model=claude-opus-4-7 parse_errors=0 tokens_in=6471 tokens_out=604
2026-05-24T03:36:45.906763Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:36:45.907430Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:36:45.908424Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:36:45.909175Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:36:45.910269Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=004.png is_anomalous=False parse_error=False
2026-05-24T03:36:45.911769Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:36:45.912775Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.65 image=006.png is_anomalous=False parse_error=False
2026-05-24T03:36:45.913492Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:36:45.914345Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:36:45.915011Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:36:54.477714Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:36:54.480689Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.14079 latency_ms=8554 model=claude-opus-4-7 parse_errors=0 tokens_in=6471 tokens_out=583
2026-05-24T03:36:54.481527Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:36:54.482214Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:36:54.483109Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:36:54.483889Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:36:54.484894Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:36:54.485556Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:36:54.486393Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:36:54.487016Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:36:54.487826Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:36:54.488478Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=019.png is_anomalous=True parse_error=False
2026-05-24T03:37:04.922785Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:37:04.925918Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.13974 latency_ms=10427 model=claude-opus-4-7 parse_errors=0 tokens_in=6471 tokens_out=569
2026-05-24T03:37:04.926591Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=020.png is_anomalous=True parse_error=False
2026-05-24T03:37:04.927301Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=021.png is_anomalous=True parse_error=False
2026-05-24T03:37:04.928177Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=022.png is_anomalous=False parse_error=False
2026-05-24T03:37:04.928821Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=023.png is_anomalous=True parse_error=False
2026-05-24T03:37:04.929678Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=024.png is_anomalous=True parse_error=False
2026-05-24T03:37:04.930397Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:37:04.931278Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:37:04.932750Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:37:04.933526Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:37:04.934336Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:37:13.873134Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:37:13.876088Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.14049 latency_ms=8932 model=claude-opus-4-7 parse_errors=0 tokens_in=6471 tokens_out=579
2026-05-24T03:37:13.876748Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:37:13.877473Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:37:13.878337Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:37:13.879046Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:37:13.879928Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:37:13.880625Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:37:13.881442Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:37:13.882069Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:37:13.882899Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:37:13.883549Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:37:22.136375Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:37:22.139365Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.13854 latency_ms=8246 model=claude-opus-4-7 parse_errors=0 tokens_in=6471 tokens_out=553
2026-05-24T03:37:22.141014Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:37:22.141900Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:37:22.142565Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:37:22.143430Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:37:22.144024Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=019.png is_anomalous=True parse_error=False
2026-05-24T03:37:22.144873Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=020.png is_anomalous=True parse_error=False
2026-05-24T03:37:22.145509Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=021.png is_anomalous=True parse_error=False
2026-05-24T03:37:22.146382Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:37:22.147072Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=001.png is_anomalous=False parse_error=False
2026-05-24T03:37:22.148056Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:37:31.445356Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:37:31.448352Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.14199 latency_ms=9290 model=claude-opus-4-7 parse_errors=0 tokens_in=6471 tokens_out=599
2026-05-24T03:37:31.449016Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=003.png is_anomalous=False parse_error=False
2026-05-24T03:37:31.449652Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=004.png is_anomalous=False parse_error=False
2026-05-24T03:37:31.450281Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=005.png is_anomalous=False parse_error=False
2026-05-24T03:37:31.451008Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=006.png is_anomalous=False parse_error=False
2026-05-24T03:37:31.451928Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:37:31.452567Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=008.png is_anomalous=False parse_error=False
2026-05-24T03:37:31.453413Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.6 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:37:31.454073Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=010.png is_anomalous=False parse_error=False
2026-05-24T03:37:31.454888Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:37:31.455545Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=012.png is_anomalous=False parse_error=False
2026-05-24T03:37:41.274915Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:37:41.277899Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.14221 latency_ms=9813 model=claude-opus-4-7 parse_errors=0 tokens_in=6471 tokens_out=602
2026-05-24T03:37:41.278576Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=013.png is_anomalous=False parse_error=False
2026-05-24T03:37:41.279235Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:37:41.280111Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=015.png is_anomalous=False parse_error=False
2026-05-24T03:37:41.280758Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:37:41.281606Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=017.png is_anomalous=False parse_error=False
2026-05-24T03:37:41.282245Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=018.png is_anomalous=False parse_error=False
2026-05-24T03:37:41.283065Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=019.png is_anomalous=True parse_error=False
2026-05-24T03:37:41.283673Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=020.png is_anomalous=False parse_error=False
2026-05-24T03:37:41.284512Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=021.png is_anomalous=False parse_error=False
2026-05-24T03:37:41.285151Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=022.png is_anomalous=False parse_error=False
2026-05-24T03:37:50.082798Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:37:50.086042Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.14042 latency_ms=8790 model=claude-opus-4-7 parse_errors=0 tokens_in=6471 tokens_out=578
2026-05-24T03:37:50.086761Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:37:50.087571Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=001.png is_anomalous=False parse_error=False
2026-05-24T03:37:50.088472Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:37:50.089372Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=003.png is_anomalous=False parse_error=False
2026-05-24T03:37:50.090522Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:37:50.091385Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.65 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:37:50.092097Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=006.png is_anomalous=False parse_error=False
2026-05-24T03:37:50.092998Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:37:50.093662Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:37:50.094528Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=009.png is_anomalous=False parse_error=False
2026-05-24T03:38:02.462865Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:38:02.466210Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.14559 latency_ms=12363 model=claude-opus-4-7 parse_errors=0 tokens_in=6471 tokens_out=647
2026-05-24T03:38:02.466963Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=010.png is_anomalous=False parse_error=False
2026-05-24T03:38:02.467801Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:38:02.469030Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=012.png is_anomalous=False parse_error=False
2026-05-24T03:38:02.470219Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=013.png is_anomalous=False parse_error=False
2026-05-24T03:38:02.471110Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=014.png is_anomalous=False parse_error=False
2026-05-24T03:38:02.472141Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:38:02.473203Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:38:02.474235Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=017.png is_anomalous=False parse_error=False
2026-05-24T03:38:02.474966Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.72 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:38:02.475813Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=019.png is_anomalous=True parse_error=False
2026-05-24T03:38:11.995398Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:38:11.998427Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.14334 latency_ms=9513 model=claude-opus-4-7 parse_errors=0 tokens_in=6471 tokens_out=617
2026-05-24T03:38:11.999157Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=020.png is_anomalous=False parse_error=False
2026-05-24T03:38:11.999811Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=021.png is_anomalous=False parse_error=False

  metal_nut     AUROC=0.802  F1=0.816  n=115  cost=$1.6293

pill:   0%|          | 0/17 [00:00<?, ?it/s]

2026-05-24T03:38:35.138189Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:38:35.141159Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.17281 latency_ms=9054 model=claude-opus-4-7 parse_errors=0 tokens_in=8631 tokens_out=578
2026-05-24T03:38:35.141884Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:38:35.142547Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:38:35.143457Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:38:35.144081Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:38:35.144913Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:38:35.145646Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:38:35.146579Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:38:35.147236Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=007.png is_anomalous=False parse_error=False
2026-05-24T03:38:35.148335Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:38:35.149053Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:38:46.077607Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:38:46.083256Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.18301 latency_ms=10924 model=claude-opus-4-7 parse_errors=0 tokens_in=8631 tokens_out=714
2026-05-24T03:38:46.083945Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=010.png is_anomalous=False parse_error=False
2026-05-24T03:38:46.084621Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:38:46.085481Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:38:46.086179Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:38:46.087186Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:38:46.087871Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:38:46.088851Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:38:46.089598Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:38:46.090583Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:38:46.091266Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=019.png is_anomalous=True parse_error=False
2026-05-24T03:38:56.847459Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:38:56.850661Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.18024 latency_ms=10750 model=claude-opus-4-7 parse_errors=0 tokens_in=8631 tokens_out=677
2026-05-24T03:38:56.851392Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=020.png is_anomalous=False parse_error=False
2026-05-24T03:38:56.852090Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=021.png is_anomalous=False parse_error=False
2026-05-24T03:38:56.853027Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=022.png is_anomalous=True parse_error=False
2026-05-24T03:38:56.853655Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=023.png is_anomalous=True parse_error=False
2026-05-24T03:38:56.854479Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=024.png is_anomalous=False parse_error=False
2026-05-24T03:38:56.855110Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:38:56.855914Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:38:56.856561Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:38:56.857463Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:38:56.858127Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:39:11.180856Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:39:11.184221Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.17807 latency_ms=14315 model=claude-opus-4-7 parse_errors=0 tokens_in=8631 tokens_out=648
2026-05-24T03:39:11.184931Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:39:11.185576Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:39:11.186448Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:39:11.187096Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:39:11.187991Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:39:11.188636Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:39:11.189552Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:39:11.190185Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:39:11.191125Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:39:11.191987Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:39:20.710608Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:39:20.713734Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.17364 latency_ms=9512 model=claude-opus-4-7 parse_errors=0 tokens_in=8631 tokens_out=589
2026-05-24T03:39:20.714524Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:39:20.715251Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:39:20.716202Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:39:20.716923Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:39:20.717811Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:39:20.718448Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:39:20.719285Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:39:20.719967Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:39:20.720789Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:39:20.721452Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:39:33.000791Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:39:33.004469Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.17356 latency_ms=12247 model=claude-opus-4-7 parse_errors=0 tokens_in=8631 tokens_out=588
2026-05-24T03:39:33.005297Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:39:33.006027Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=009.png is_anomalous=False parse_error=False
2026-05-24T03:39:33.007015Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:39:33.007677Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:39:33.008543Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:39:33.009208Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:39:33.009995Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:39:33.010614Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:39:33.011363Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:39:33.011968Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:39:44.019156Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:39:44.022372Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.17814 latency_ms=11001 model=claude-opus-4-7 parse_errors=0 tokens_in=8631 tokens_out=649
2026-05-24T03:39:44.023060Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:39:44.023714Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=019.png is_anomalous=True parse_error=False
2026-05-24T03:39:44.024564Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=020.png is_anomalous=False parse_error=False
2026-05-24T03:39:44.025208Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:39:44.026042Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=001.png is_anomalous=False parse_error=False
2026-05-24T03:39:44.026657Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:39:44.027490Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:39:44.028183Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:39:44.028958Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:39:44.029635Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:39:55.522976Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:39:55.526071Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.17716 latency_ms=11487 model=claude-opus-4-7 parse_errors=0 tokens_in=8631 tokens_out=636
2026-05-24T03:39:55.526806Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=007.png is_anomalous=False parse_error=False
2026-05-24T03:39:55.527477Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=008.png is_anomalous=False parse_error=False
2026-05-24T03:39:55.528380Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:39:55.529050Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:39:55.529921Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:39:55.530551Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:39:55.531362Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=013.png is_anomalous=False parse_error=False
2026-05-24T03:39:55.532012Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:39:55.532856Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:39:55.533489Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=016.png is_anomalous=False parse_error=False
2026-05-24T03:40:04.828512Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:40:04.831904Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.17454 latency_ms=9288 model=claude-opus-4-7 parse_errors=0 tokens_in=8631 tokens_out=601
2026-05-24T03:40:04.832597Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:40:04.833247Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:40:04.834225Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=019.png is_anomalous=True parse_error=False
2026-05-24T03:40:04.834853Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=020.png is_anomalous=False parse_error=False
2026-05-24T03:40:04.835703Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=021.png is_anomalous=True parse_error=False
2026-05-24T03:40:04.836365Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=022.png is_anomalous=True parse_error=False
2026-05-24T03:40:04.837209Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=023.png is_anomalous=True parse_error=False
2026-05-24T03:40:04.837914Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=024.png is_anomalous=False parse_error=False
2026-05-24T03:40:04.838742Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=025.png is_anomalous=True parse_error=False
2026-05-24T03:40:04.839372Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:40:16.879965Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:40:16.883190Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.17694 latency_ms=12033 model=claude-opus-4-7 parse_errors=0 tokens_in=8631 tokens_out=633
2026-05-24T03:40:16.883890Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:40:16.884544Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=002.png is_anomalous=False parse_error=False

  pill          AUROC=0.894  F1=0.901  n=167  cost=$2.9504

screw:   0%|          | 0/16 [00:00<?, ?it/s]

2026-05-24T03:41:36.492988Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:41:36.496443Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25292 latency_ms=11212 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=590
2026-05-24T03:41:36.497133Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:41:36.497849Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=001.png is_anomalous=False parse_error=False
2026-05-24T03:41:36.498780Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:41:36.499475Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:41:36.500298Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:41:36.500909Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:41:36.501716Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=006.png is_anomalous=False parse_error=False
2026-05-24T03:41:36.502399Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=007.png is_anomalous=False parse_error=False
2026-05-24T03:41:36.503236Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.65 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:41:36.503849Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=009.png is_anomalous=False parse_error=False
2026-05-24T03:41:46.942375Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:41:46.945487Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25524 latency_ms=10432 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=621
2026-05-24T03:41:46.946209Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=010.png is_anomalous=False parse_error=False
2026-05-24T03:41:46.946904Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:41:46.947832Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:41:46.948533Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:41:46.949505Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.65 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:41:46.950136Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=015.png is_anomalous=False parse_error=False
2026-05-24T03:41:46.950919Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.6 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:41:46.951500Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:41:46.952279Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=018.png is_anomalous=False parse_error=False
2026-05-24T03:41:46.952885Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=019.png is_anomalous=True parse_error=False
2026-05-24T03:41:56.152675Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:41:56.155702Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25314 latency_ms=9193 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=593
2026-05-24T03:41:56.156389Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=020.png is_anomalous=False parse_error=False
2026-05-24T03:41:56.157033Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=021.png is_anomalous=False parse_error=False
2026-05-24T03:41:56.157889Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=022.png is_anomalous=True parse_error=False
2026-05-24T03:41:56.158552Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=023.png is_anomalous=True parse_error=False
2026-05-24T03:41:56.159445Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=024.png is_anomalous=False parse_error=False
2026-05-24T03:41:56.160079Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=025.png is_anomalous=False parse_error=False
2026-05-24T03:41:56.160905Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=026.png is_anomalous=False parse_error=False
2026-05-24T03:41:56.161549Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=027.png is_anomalous=False parse_error=False
2026-05-24T03:41:56.162436Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=028.png is_anomalous=True parse_error=False
2026-05-24T03:41:56.163107Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.65 image=029.png is_anomalous=True parse_error=False
2026-05-24T03:42:09.318850Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:42:09.323156Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25224 latency_ms=13149 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=581
2026-05-24T03:42:09.323929Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=030.png is_anomalous=True parse_error=False
2026-05-24T03:42:09.324767Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=031.png is_anomalous=False parse_error=False
2026-05-24T03:42:09.325742Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=032.png is_anomalous=False parse_error=False
2026-05-24T03:42:09.326385Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=033.png is_anomalous=False parse_error=False
2026-05-24T03:42:09.327168Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=034.png is_anomalous=True parse_error=False
2026-05-24T03:42:09.327834Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=035.png is_anomalous=True parse_error=False
2026-05-24T03:42:09.328814Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=036.png is_anomalous=False parse_error=False
2026-05-24T03:42:09.329581Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=037.png is_anomalous=False parse_error=False
2026-05-24T03:42:09.330766Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=038.png is_anomalous=False parse_error=False
2026-05-24T03:42:09.332037Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=039.png is_anomalous=False parse_error=False
2026-05-24T03:42:19.092158Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:42:19.095277Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25501 latency_ms=9753 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=618
2026-05-24T03:42:19.095985Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=040.png is_anomalous=False parse_error=False
2026-05-24T03:42:19.096625Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:42:19.097577Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:42:19.098277Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:42:19.099141Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:42:19.099777Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:42:19.100600Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:42:19.101206Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:42:19.102074Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:42:19.102722Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:42:28.299014Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:42:28.302522Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25112 latency_ms=9190 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=566
2026-05-24T03:42:28.303259Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=009.png is_anomalous=False parse_error=False
2026-05-24T03:42:28.303987Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:42:28.304869Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:42:28.305537Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=012.png is_anomalous=False parse_error=False
2026-05-24T03:42:28.306344Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:42:28.307075Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:42:28.308009Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:42:28.308637Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:42:28.309685Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=017.png is_anomalous=False parse_error=False
2026-05-24T03:42:28.310368Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:42:38.639358Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:42:38.642597Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25367 latency_ms=10329 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=600
2026-05-24T03:42:38.643291Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=019.png is_anomalous=True parse_error=False
2026-05-24T03:42:38.643895Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=020.png is_anomalous=False parse_error=False
2026-05-24T03:42:38.644523Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=021.png is_anomalous=True parse_error=False
2026-05-24T03:42:38.645381Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=022.png is_anomalous=True parse_error=False
2026-05-24T03:42:38.646101Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=023.png is_anomalous=False parse_error=False
2026-05-24T03:42:38.646758Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:42:38.647574Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:42:38.648222Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:42:38.649036Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:42:38.649677Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=004.png is_anomalous=False parse_error=False
2026-05-24T03:42:49.387723Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:42:49.390834Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25501 latency_ms=10734 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=618
2026-05-24T03:42:49.391513Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:42:49.392197Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:42:49.393155Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:42:49.393787Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:42:49.394651Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:42:49.395283Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=010.png is_anomalous=False parse_error=False
2026-05-24T03:42:49.396109Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:42:49.396727Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:42:49.397539Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:42:49.398140Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.83 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:42:59.735938Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:42:59.739173Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25562 latency_ms=10333 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=626
2026-05-24T03:42:59.739851Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:42:59.740545Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:42:59.741388Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=017.png is_anomalous=False parse_error=False
2026-05-24T03:42:59.742050Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:42:59.742909Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=019.png is_anomalous=True parse_error=False
2026-05-24T03:42:59.743711Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=020.png is_anomalous=True parse_error=False
2026-05-24T03:42:59.744647Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=021.png is_anomalous=True parse_error=False
2026-05-24T03:42:59.745439Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=022.png is_anomalous=True parse_error=False
2026-05-24T03:42:59.746177Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=023.png is_anomalous=True parse_error=False
2026-05-24T03:42:59.746794Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:43:10.790062Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:43:10.793287Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25419 latency_ms=11037 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=607
2026-05-24T03:43:10.794053Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=001.png is_anomalous=False parse_error=False
2026-05-24T03:43:10.794858Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=002.png is_anomalous=True parse_error=False

  screw         AUROC=0.783  F1=0.784  n=160  cost=$4.0600

tile:   0%|          | 0/12 [00:00<?, ?it/s]

2026-05-24T03:44:27.579615Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:44:27.582784Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.18759 latency_ms=12746 model=claude-opus-4-7 parse_errors=0 tokens_in=9221 tokens_out=657
2026-05-24T03:44:27.583467Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.98 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:44:27.584352Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:44:27.585183Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.98 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:44:27.585987Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.98 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:44:27.586865Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:44:27.587545Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:44:27.588536Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.98 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:44:27.589259Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:44:27.590292Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:44:27.591045Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.98 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:44:38.907978Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:44:38.911423Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.18541 latency_ms=11309 model=claude-opus-4-7 parse_errors=0 tokens_in=9221 tokens_out=628
2026-05-24T03:44:38.912262Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.98 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:44:38.913057Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:44:38.913843Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.98 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:44:38.914505Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:44:38.915533Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:44:38.916240Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:44:38.917038Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:44:38.917616Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:44:38.918417Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:44:38.919031Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:44:47.805184Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:44:47.808204Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.18594 latency_ms=8877 model=claude-opus-4-7 parse_errors=0 tokens_in=9221 tokens_out=635
2026-05-24T03:44:47.808842Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:44:47.809564Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:44:47.810469Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:44:47.811091Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:44:47.812032Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:44:47.812717Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:44:47.813785Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:44:47.814532Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:44:47.815426Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:44:47.816107Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:44:56.613556Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:44:56.616717Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.18159 latency_ms=8790 model=claude-opus-4-7 parse_errors=0 tokens_in=9221 tokens_out=577
2026-05-24T03:44:56.617433Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:44:56.618100Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:44:56.618970Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:44:56.619584Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:44:56.620413Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:44:56.621035Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:44:56.628342Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=001.png is_anomalous=False parse_error=False
2026-05-24T03:44:56.629381Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:44:56.630259Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=003.png is_anomalous=False parse_error=False
2026-05-24T03:44:56.631229Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=004.png is_anomalous=False parse_error=False
2026-05-24T03:45:05.743994Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:45:05.747100Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.17986 latency_ms=9105 model=claude-opus-4-7 parse_errors=0 tokens_in=9221 tokens_out=554
2026-05-24T03:45:05.747845Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=005.png is_anomalous=False parse_error=False
2026-05-24T03:45:05.748481Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=006.png is_anomalous=False parse_error=False
2026-05-24T03:45:05.749397Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.83 image=007.png is_anomalous=False parse_error=False
2026-05-24T03:45:05.750036Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=008.png is_anomalous=False parse_error=False
2026-05-24T03:45:05.750924Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:45:05.751552Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=010.png is_anomalous=False parse_error=False
2026-05-24T03:45:05.752393Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=011.png is_anomalous=False parse_error=False
2026-05-24T03:45:05.753042Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=012.png is_anomalous=False parse_error=False
2026-05-24T03:45:05.753909Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=013.png is_anomalous=False parse_error=False
2026-05-24T03:45:05.754534Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.81 image=014.png is_anomalous=False parse_error=False
2026-05-24T03:45:15.683759Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:45:15.686968Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.18099 latency_ms=9921 model=claude-opus-4-7 parse_errors=0 tokens_in=9221 tokens_out=569
2026-05-24T03:45:15.687664Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.72 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:45:15.688304Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=016.png is_anomalous=False parse_error=False
2026-05-24T03:45:15.689119Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:45:15.689878Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=018.png is_anomalous=False parse_error=False
2026-05-24T03:45:15.690751Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=019.png is_anomalous=False parse_error=False
2026-05-24T03:45:15.691412Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=020.png is_anomalous=False parse_error=False
2026-05-24T03:45:15.692254Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.77 image=021.png is_anomalous=False parse_error=False
2026-05-24T03:45:15.692868Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.74 image=022.png is_anomalous=False parse_error=False
2026-05-24T03:45:15.693695Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.73 image=023.png is_anomalous=False parse_error=False
2026-05-24T03:45:15.694329Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.76 image=024.png is_anomalous=False parse_error=False
2026-05-24T03:45:24.673008Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:45:24.676410Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.17934 latency_ms=8971 model=claude-opus-4-7 parse_errors=0 tokens_in=9221 tokens_out=547
2026-05-24T03:45:24.677116Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=025.png is_anomalous=False parse_error=False
2026-05-24T03:45:24.677906Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=026.png is_anomalous=False parse_error=False
2026-05-24T03:45:24.678802Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=027.png is_anomalous=False parse_error=False
2026-05-24T03:45:24.679443Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=028.png is_anomalous=False parse_error=False
2026-05-24T03:45:24.680432Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=029.png is_anomalous=False parse_error=False
2026-05-24T03:45:24.681061Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=030.png is_anomalous=False parse_error=False
2026-05-24T03:45:24.681948Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=031.png is_anomalous=False parse_error=False
2026-05-24T03:45:24.682565Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=032.png is_anomalous=False parse_error=False
2026-05-24T03:45:24.683386Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:45:24.684051Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:45:34.809089Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:45:34.812496Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.18136 latency_ms=10119 model=claude-opus-4-7 parse_errors=0 tokens_in=9221 tokens_out=574
2026-05-24T03:45:34.813196Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:45:34.813826Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:45:34.814629Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:45:34.815265Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:45:34.816120Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:45:34.816762Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:45:34.817560Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:45:34.818191Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:45:34.818970Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:45:34.819582Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:45:45.766042Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:45:45.769160Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.18796 latency_ms=10939 model=claude-opus-4-7 parse_errors=0 tokens_in=9221 tokens_out=662
2026-05-24T03:45:45.769847Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:45:45.770479Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:45:45.771334Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:45:45.772051Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:45:45.772859Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:45:45.773551Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:45:45.774431Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:45:45.775224Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:45:45.776041Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:45:45.776696Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:45:55.227213Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:45:55.230231Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.18271 latency_ms=9442 model=claude-opus-4-7 parse_errors=0 tokens_in=9221 tokens_out=592
2026-05-24T03:45:55.230941Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:45:55.231635Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=007.png is_anomalous=True parse_error=False

  tile          AUROC=0.995  F1=0.958  n=117  cost=$2.1588

toothbrush:   0%|          | 0/5 [00:00<?, ?it/s]

2026-05-24T03:46:28.380899Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:46:28.384402Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25944 latency_ms=10975 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=677
2026-05-24T03:46:28.385355Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:46:28.386155Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:46:28.387262Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:46:28.388393Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:46:28.389848Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:46:28.391285Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:46:28.392605Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:46:28.394042Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:46:28.395282Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:46:28.396239Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:46:39.659947Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:46:39.663871Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25479 latency_ms=11256 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=615
2026-05-24T03:46:39.664565Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:46:39.665217Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:46:39.666076Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:46:39.666765Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:46:39.667593Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:46:39.668230Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:46:39.669397Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:46:39.669999Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:46:39.670844Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.6 image=018.png is_anomalous=False parse_error=False
2026-05-24T03:46:39.671519Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=019.png is_anomalous=True parse_error=False
2026-05-24T03:46:51.287456Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:46:51.290856Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25922 latency_ms=11609 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=674
2026-05-24T03:46:51.291580Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=020.png is_anomalous=True parse_error=False
2026-05-24T03:46:51.292374Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=021.png is_anomalous=True parse_error=False
2026-05-24T03:46:51.293393Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=022.png is_anomalous=True parse_error=False
2026-05-24T03:46:51.294088Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=023.png is_anomalous=True parse_error=False
2026-05-24T03:46:51.294986Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=024.png is_anomalous=True parse_error=False
2026-05-24T03:46:51.295721Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=025.png is_anomalous=True parse_error=False
2026-05-24T03:46:51.296535Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=026.png is_anomalous=True parse_error=False
2026-05-24T03:46:51.297238Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=027.png is_anomalous=False parse_error=False
2026-05-24T03:46:51.298027Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=028.png is_anomalous=True parse_error=False
2026-05-24T03:46:51.298646Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=029.png is_anomalous=True parse_error=False
2026-05-24T03:47:02.367357Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:47:02.371779Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25449 latency_ms=11062 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=611
2026-05-24T03:47:02.372569Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:47:02.373379Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=001.png is_anomalous=False parse_error=False
2026-05-24T03:47:02.374467Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:47:02.375166Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:47:02.376289Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:47:02.376976Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:47:02.377947Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:47:02.378596Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=007.png is_anomalous=False parse_error=False
2026-05-24T03:47:02.379396Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:47:02.380016Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=009.png is_anomalous=False parse_error=False
2026-05-24T03:47:06.868141Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:47:06.870983Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=2 cost_usd=0.05554 latency_ms=4481 model=claude-opus-4-7 parse_errors=0 tokens_in=2903 tokens_out=160
2026-05-24T03:47:06.871726Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:47:06.872438Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=011.png is_anomalous=False parse_error=False

  toothbrush    AUROC=0.872  F1=0.848  n=42  cost=$1.0835

transistor:   0%|          | 0/10 [00:00<?, ?it/s]

2026-05-24T03:47:19.259971Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:47:19.266435Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.26019 latency_ms=12360 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=687
2026-05-24T03:47:19.267196Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:47:19.267859Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:47:19.268993Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:47:19.269639Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:47:19.270605Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:47:19.271286Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:47:19.272169Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:47:19.272797Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:47:19.273613Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=008.png is_anomalous=False parse_error=False
2026-05-24T03:47:19.274343Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:47:29.006694Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:47:29.009851Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25284 latency_ms=9724 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=589
2026-05-24T03:47:29.010585Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:47:29.011292Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:47:29.012392Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:47:29.013159Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:47:29.013990Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:47:29.014596Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=005.png is_anomalous=False parse_error=False
2026-05-24T03:47:29.015472Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:47:29.016102Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=007.png is_anomalous=False parse_error=False
2026-05-24T03:47:29.016983Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:47:29.017643Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:47:40.406195Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:47:40.409379Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25696 latency_ms=11380 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=644
2026-05-24T03:47:40.410056Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:47:40.410720Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:47:40.411619Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:47:40.412240Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:47:40.413197Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:47:40.413823Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:47:40.414657Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:47:40.415346Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:47:40.416226Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:47:40.416910Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:47:51.136289Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:47:51.149244Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25344 latency_ms=10718 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=597
2026-05-24T03:47:51.150171Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:47:51.152672Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=001.png is_anomalous=False parse_error=False
2026-05-24T03:47:51.154522Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:47:51.155635Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:47:51.156433Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=004.png is_anomalous=False parse_error=False
2026-05-24T03:47:51.157398Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.65 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:47:51.158225Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=006.png is_anomalous=False parse_error=False
2026-05-24T03:47:51.164439Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=007.png is_anomalous=False parse_error=False
2026-05-24T03:47:51.165315Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:47:51.166514Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=009.png is_anomalous=False parse_error=False
2026-05-24T03:48:03.340552Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:48:03.343796Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25337 latency_ms=12158 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=596
2026-05-24T03:48:03.344637Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=010.png is_anomalous=False parse_error=False
2026-05-24T03:48:03.345373Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:48:03.346143Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.65 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:48:03.346798Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=013.png is_anomalous=False parse_error=False
2026-05-24T03:48:03.347649Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=014.png is_anomalous=False parse_error=False
2026-05-24T03:48:03.348368Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.6 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:48:03.349158Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.55 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:48:03.349888Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=017.png is_anomalous=False parse_error=False
2026-05-24T03:48:03.350931Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:48:03.351783Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=019.png is_anomalous=False parse_error=False
2026-05-24T03:48:13.748633Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:48:13.751778Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25044 latency_ms=10388 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=557
2026-05-24T03:48:13.752626Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=020.png is_anomalous=False parse_error=False
2026-05-24T03:48:13.753362Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=021.png is_anomalous=False parse_error=False
2026-05-24T03:48:13.754187Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=022.png is_anomalous=False parse_error=False
2026-05-24T03:48:13.754840Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=023.png is_anomalous=False parse_error=False
2026-05-24T03:48:13.755736Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=024.png is_anomalous=True parse_error=False
2026-05-24T03:48:13.756362Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=025.png is_anomalous=False parse_error=False
2026-05-24T03:48:13.757212Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=026.png is_anomalous=False parse_error=False
2026-05-24T03:48:13.757840Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=027.png is_anomalous=False parse_error=False
2026-05-24T03:48:13.758648Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=028.png is_anomalous=True parse_error=False
2026-05-24T03:48:13.759257Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=029.png is_anomalous=True parse_error=False
2026-05-24T03:48:25.277081Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:48:25.280255Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25472 latency_ms=11510 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=614
2026-05-24T03:48:25.280934Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=030.png is_anomalous=False parse_error=False
2026-05-24T03:48:25.281565Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=031.png is_anomalous=False parse_error=False
2026-05-24T03:48:25.282375Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=032.png is_anomalous=False parse_error=False
2026-05-24T03:48:25.283183Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=033.png is_anomalous=False parse_error=False
2026-05-24T03:48:25.284077Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=034.png is_anomalous=True parse_error=False
2026-05-24T03:48:25.284865Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=035.png is_anomalous=False parse_error=False
2026-05-24T03:48:25.285684Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=036.png is_anomalous=False parse_error=False
2026-05-24T03:48:25.286315Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=037.png is_anomalous=False parse_error=False
2026-05-24T03:48:25.287234Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.6 image=038.png is_anomalous=True parse_error=False
2026-05-24T03:48:25.288050Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=039.png is_anomalous=True parse_error=False
2026-05-24T03:48:35.901080Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:48:35.906189Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25351 latency_ms=10606 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=598
2026-05-24T03:48:35.907296Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=040.png is_anomalous=True parse_error=False
2026-05-24T03:48:35.908416Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=041.png is_anomalous=False parse_error=False
2026-05-24T03:48:35.910064Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=042.png is_anomalous=False parse_error=False
2026-05-24T03:48:35.911187Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=043.png is_anomalous=True parse_error=False
2026-05-24T03:48:35.911941Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=044.png is_anomalous=True parse_error=False
2026-05-24T03:48:35.912916Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=045.png is_anomalous=False parse_error=False
2026-05-24T03:48:35.914780Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.6 image=046.png is_anomalous=True parse_error=False
2026-05-24T03:48:35.915926Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=047.png is_anomalous=False parse_error=False
2026-05-24T03:48:35.917224Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=048.png is_anomalous=True parse_error=False
2026-05-24T03:48:35.919417Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=049.png is_anomalous=True parse_error=False
2026-05-24T03:48:46.555836Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:48:46.558981Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25554 latency_ms=10620 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=625
2026-05-24T03:48:46.559666Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=050.png is_anomalous=False parse_error=False
2026-05-24T03:48:46.560352Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=051.png is_anomalous=True parse_error=False
2026-05-24T03:48:46.562042Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=052.png is_anomalous=True parse_error=False
2026-05-24T03:48:46.562890Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=053.png is_anomalous=False parse_error=False
2026-05-24T03:48:46.563562Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=054.png is_anomalous=True parse_error=False
2026-05-24T03:48:46.564357Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.6 image=055.png is_anomalous=True parse_error=False
2026-05-24T03:48:46.565064Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=056.png is_anomalous=True parse_error=False
2026-05-24T03:48:46.565969Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=057.png is_anomalous=False parse_error=False
2026-05-24T03:48:46.566604Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=058.png is_anomalous=True parse_error=False
2026-05-24T03:48:46.567436Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=059.png is_anomalous=False parse_error=False
2026-05-24T03:48:58.148338Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:48:58.152523Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25959 latency_ms=11572 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=679
2026-05-24T03:48:58.153479Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:48:58.154620Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=001.png is_anomalous=True parse_error=False

  transistor    AUROC=0.696  F1=0.589  n=100  cost=$2.5506

wood:   0%|          | 0/8 [00:00<?, ?it/s]

2026-05-24T03:49:07.899633Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:49:07.902870Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25172 latency_ms=9620 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=574
2026-05-24T03:49:07.903554Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:49:07.904197Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:49:07.905026Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:49:07.905800Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:49:07.906666Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:49:07.907402Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:49:07.908235Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:49:07.908893Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:49:07.909735Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:49:07.910329Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:49:20.079372Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:49:20.082480Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25644 latency_ms=12161 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=637
2026-05-24T03:49:20.083193Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:49:20.084181Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:49:20.085807Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:49:20.090058Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:49:20.091089Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.87 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:49:20.091814Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:49:20.092716Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.86 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:49:20.093349Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:49:20.094283Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:49:20.095059Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:49:30.351565Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:49:30.354613Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25119 latency_ms=10249 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=567
2026-05-24T03:49:30.355346Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:49:30.356021Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:49:30.356843Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=003.png is_anomalous=False parse_error=False
2026-05-24T03:49:30.357454Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.86 image=004.png is_anomalous=False parse_error=False
2026-05-24T03:49:30.358443Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.84 image=005.png is_anomalous=False parse_error=False
2026-05-24T03:49:30.359089Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.83 image=006.png is_anomalous=False parse_error=False
2026-05-24T03:49:30.359932Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=007.png is_anomalous=False parse_error=False
2026-05-24T03:49:30.360593Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.6 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:49:30.361538Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.65 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:49:30.362335Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=010.png is_anomalous=False parse_error=False
2026-05-24T03:49:40.263238Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:49:40.266388Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25217 latency_ms=9893 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=580
2026-05-24T03:49:40.267044Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=011.png is_anomalous=False parse_error=False
2026-05-24T03:49:40.267675Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=012.png is_anomalous=False parse_error=False
2026-05-24T03:49:40.268369Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=013.png is_anomalous=False parse_error=False
2026-05-24T03:49:40.269249Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=014.png is_anomalous=False parse_error=False
2026-05-24T03:49:40.269907Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=015.png is_anomalous=False parse_error=False
2026-05-24T03:49:40.270910Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=016.png is_anomalous=False parse_error=False
2026-05-24T03:49:40.280351Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=017.png is_anomalous=False parse_error=False
2026-05-24T03:49:40.281268Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.83 image=018.png is_anomalous=False parse_error=False
2026-05-24T03:49:40.281979Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:49:40.282817Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:49:50.507947Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:49:50.511143Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25217 latency_ms=10218 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=580
2026-05-24T03:49:50.511826Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:49:50.512474Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:49:50.513536Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.96 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:49:50.514195Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.97 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:49:50.515064Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:49:50.515740Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:49:50.516641Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:49:50.517281Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:49:50.518043Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:49:50.518784Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:50:01.787155Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:50:01.790808Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25606 latency_ms=11260 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=632
2026-05-24T03:50:01.791503Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:50:01.792216Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:50:01.793103Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:50:01.794059Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:50:01.795049Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:50:01.795645Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:50:01.796557Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:50:01.797208Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:50:01.798119Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:50:01.798748Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:50:15.072149Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:50:15.075253Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25539 latency_ms=13266 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=623
2026-05-24T03:50:15.076199Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=002.png is_anomalous=True parse_error=False
2026-05-24T03:50:15.077072Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:50:15.077983Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:50:15.078727Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:50:15.079823Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:50:15.081099Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:50:15.083648Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:50:15.085798Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:50:15.086914Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:50:15.087606Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.91 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:50:25.402094Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:50:25.405267Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=9 cost_usd=0.22875 latency_ms=10307 model=claude-opus-4-7 parse_errors=0 tokens_in=12535 tokens_out=543
2026-05-24T03:50:25.405945Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:50:25.406609Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:50:25.407517Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:50:25.408128Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:50:25.409052Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:50:25.409759Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:50:25.410636Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:50:25.411276Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=019.png is_anomalous=True parse_error=False
2026-05-24T03:50:25.412132Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=020.png is_anomalous=True parse_error=False

  wood          AUROC=0.999  F1=0.976  n=79  cost=$2.0039

zipper:   0%|          | 0/16 [00:00<?, ?it/s]

2026-05-24T03:50:37.494373Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:50:37.499302Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.26079 latency_ms=12021 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=695
2026-05-24T03:50:37.500609Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:50:37.501636Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:50:37.503117Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:50:37.504606Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.95 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:50:37.506071Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:50:37.507596Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:50:37.508909Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:50:37.509852Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:50:37.511239Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=008.png is_anomalous=False parse_error=False
2026-05-24T03:50:37.512618Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.78 image=009.png is_anomalous=False parse_error=False
2026-05-24T03:50:48.941763Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:50:48.944816Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25817 latency_ms=11416 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=660
2026-05-24T03:50:48.945495Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:50:48.946106Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:50:48.946761Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:50:48.947512Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:50:48.948344Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:50:48.949039Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=015.png is_anomalous=False parse_error=False
2026-05-24T03:50:48.949855Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:50:48.950453Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=017.png is_anomalous=True parse_error=False
2026-05-24T03:50:48.951234Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=018.png is_anomalous=True parse_error=False
2026-05-24T03:50:48.951873Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:51:00.222895Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:51:00.226732Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25937 latency_ms=11264 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=676
2026-05-24T03:51:00.227764Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=001.png is_anomalous=False parse_error=False
2026-05-24T03:51:00.228479Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:51:00.229458Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:51:00.230276Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:51:00.231242Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:51:00.231929Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:51:00.232980Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:51:00.233984Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:51:00.235015Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:51:00.235835Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:51:10.278093Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:51:10.281358Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25389 latency_ms=10032 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=603
2026-05-24T03:51:10.282064Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:51:10.282746Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:51:10.283680Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:51:10.284318Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:51:10.285179Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:51:10.293355Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:51:10.294849Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:51:10.296332Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.6 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:51:10.297365Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:51:10.298166Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:51:24.452257Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:51:24.455537Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25322 latency_ms=14146 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=594
2026-05-24T03:51:24.456253Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:51:24.456903Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.93 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:51:24.457641Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=007.png is_anomalous=True parse_error=False
2026-05-24T03:51:24.458438Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:51:24.459290Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.94 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:51:24.459880Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:51:24.460716Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:51:24.461333Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=012.png is_anomalous=True parse_error=False
2026-05-24T03:51:24.462293Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:51:24.462951Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.87 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:51:34.749486Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:51:34.752513Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25472 latency_ms=10280 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=614
2026-05-24T03:51:34.753201Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:51:34.753872Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=016.png is_anomalous=True parse_error=False
2026-05-24T03:51:34.754705Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.75 image=000.png is_anomalous=True parse_error=False
2026-05-24T03:51:34.755377Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=001.png is_anomalous=True parse_error=False
2026-05-24T03:51:34.756185Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.6 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:51:34.756805Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=003.png is_anomalous=True parse_error=False
2026-05-24T03:51:34.757651Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=004.png is_anomalous=True parse_error=False
2026-05-24T03:51:34.758297Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=005.png is_anomalous=True parse_error=False
2026-05-24T03:51:34.759359Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=006.png is_anomalous=True parse_error=False
2026-05-24T03:51:34.760057Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.55 image=007.png is_anomalous=False parse_error=False
2026-05-24T03:51:45.023019Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:51:45.026942Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25599 latency_ms=10257 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=631
2026-05-24T03:51:45.027897Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.92 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:51:45.028628Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=009.png is_anomalous=True parse_error=False
2026-05-24T03:51:45.029541Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=010.png is_anomalous=True parse_error=False
2026-05-24T03:51:45.030368Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=011.png is_anomalous=True parse_error=False
2026-05-24T03:51:45.031613Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.9 image=012.png is_anomalous=False parse_error=False
2026-05-24T03:51:45.032345Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=013.png is_anomalous=True parse_error=False
2026-05-24T03:51:45.033564Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.82 image=014.png is_anomalous=True parse_error=False
2026-05-24T03:51:45.034417Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=015.png is_anomalous=True parse_error=False
2026-05-24T03:51:45.035555Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=000.png is_anomalous=False parse_error=False
2026-05-24T03:51:45.036435Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.88 image=001.png is_anomalous=False parse_error=False
2026-05-24T03:51:54.411406Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:51:54.414857Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25141 latency_ms=9368 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=570
2026-05-24T03:51:54.415563Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=002.png is_anomalous=False parse_error=False
2026-05-24T03:51:54.416362Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=003.png is_anomalous=False parse_error=False
2026-05-24T03:51:54.417227Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=004.png is_anomalous=False parse_error=False
2026-05-24T03:51:54.417853Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=005.png is_anomalous=False parse_error=False
2026-05-24T03:51:54.418682Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=006.png is_anomalous=False parse_error=False
2026-05-24T03:51:54.419301Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=007.png is_anomalous=False parse_error=False
2026-05-24T03:51:54.420104Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.7 image=008.png is_anomalous=True parse_error=False
2026-05-24T03:51:54.420782Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=009.png is_anomalous=False parse_error=False
2026-05-24T03:51:54.421664Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=010.png is_anomalous=False parse_error=False
2026-05-24T03:51:54.422525Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=011.png is_anomalous=False parse_error=False
2026-05-24T03:52:03.719544Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:52:03.722999Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25599 latency_ms=9285 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=631
2026-05-24T03:52:03.723751Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=012.png is_anomalous=False parse_error=False
2026-05-24T03:52:03.724554Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=013.png is_anomalous=False parse_error=False
2026-05-24T03:52:03.725516Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=014.png is_anomalous=False parse_error=False
2026-05-24T03:52:03.726289Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=015.png is_anomalous=False parse_error=False
2026-05-24T03:52:03.727204Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=016.png is_anomalous=False parse_error=False
2026-05-24T03:52:03.728162Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=017.png is_anomalous=False parse_error=False
2026-05-24T03:52:03.729133Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=018.png is_anomalous=False parse_error=False
2026-05-24T03:52:03.729733Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=019.png is_anomalous=False parse_error=False
2026-05-24T03:52:03.730824Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=020.png is_anomalous=False parse_error=False
2026-05-24T03:52:03.731642Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.8 image=021.png is_anomalous=False parse_error=False
2026-05-24T03:52:15.199987Z [info     ] HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK" [httpx]
2026-05-24T03:52:15.204240Z [info     ] anthropic.predict_batch        [vlm_anomaly.backends.anthropic_backend] batch_size=10 cost_usd=0.25464 latency_ms=11461 model=claude-opus-4-7 parse_errors=0 tokens_in=13911 tokens_out=613
2026-05-24T03:52:15.205093Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=022.png is_anomalous=False parse_error=False
2026-05-24T03:52:15.205753Z [info     ] anthropic.predict_batch.item   [vlm_anomaly.backends.anthropic_backend] confidence=0.85 image=023.png is_anomalous=False parse_error=False

  zipper        AUROC=0.873  F1=0.849  n=151  cost=$3.8712

Done. Total cost this run: $34.9203

In [7]:
# ── Cell 7b: Leaderboard v2─────────────────────────────────────────────────────
import importlib
import vlm_anomaly.analysis.aggregator as _agg_mod
importlib.reload(_agg_mod)
from vlm_anomaly.analysis.aggregator import leaderboard, cost_accuracy_table

lb = leaderboard(RESULTS_DIR)
if lb.empty:
    print('No results yet.')
else:
    summary = cost_accuracy_table(RESULTS_DIR)
    print('=== Summary (mean across categories) ===')
    print(summary[["model_id","mean_auroc","mean_latency_ms"]].to_string(index=False))
    print()
    print('=== Per-category breakdown (all models) ===')
    clean = lb[lb["model_id"].notna() & lb["category"].notna() & (lb["n_images"] > 10)]
    display(
        clean[["model_id","category","n_images","auroc","f1","mean_latency_ms"]]
        .sort_values(["model_id","auroc"], ascending=[True,False])
        .reset_index(drop=True)
    )

/Users/sabareeswarans/Projects_26/VLM-Anomaly/src/vlm_anomaly/analysis/aggregator.py:78: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat(frames, ignore_index=True)
/Users/sabareeswarans/Projects_26/VLM-Anomaly/src/vlm_anomaly/analysis/aggregator.py:78: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat(frames, ignore_index=True)

=== Summary (mean across categories) ===
                             model_id  mean_auroc  mean_latency_ms
            anthropic/claude-opus-4-7    0.751931      1080.101496
              gemini/gemini-2.5-flash    0.610432      3971.451703
openrouter/qwen/qwen3-vl-32b-instruct    0.178223      2122.039152
         claude_cli/claude-sonnet-4-6         NaN      7117.170888

=== Per-category breakdown (all models) ===

,model_id,category,n_images,auroc,f1,mean_latency_ms
0,anthropic/claude-opus-4-7,bottle,83,0.910317,0.854839,1030.439475
1,anthropic/claude-opus-4-7,tile,117,0.908009,0.958084,1045.406576
2,anthropic/claude-opus-4-7,wood,79,0.890351,0.975610,1100.915710
3,anthropic/claude-opus-4-7,cable,150,0.885026,0.857143,1206.414767
4,anthropic/claude-opus-4-7,hazelnut,110,0.870893,0.832117,1046.069879
5,anthropic/claude-opus-4-7,toothbrush,42,0.851389,0.848485,1175.806569
6,anthropic/claude-opus-4-7,metal_nut,115,0.826246,0.816092,954.926203
7,anthropic/claude-opus-4-7,grid,78,0.796157,0.982456,1091.513829
8,anthropic/claude-opus-4-7,leather,124,0.706861,0.994595,989.908377
9,anthropic/claude-opus-4-7,transistor,100,0.698958,0.589474,1110.370656
10,anthropic/claude-opus-4-7,pill,167,0.689989,0.900763,1070.672708
11,anthropic/claude-opus-4-7,carpet,117,0.687801,0.972067,1089.040622
12,anthropic/claude-opus-4-7,zipper,151,0.580357,0.849057,1146.457497
13,anthropic/claude-opus-4-7,screw,160,0.538840,0.784141,1057.621746
14,anthropic/claude-opus-4-7,capsule,132,0.437774,0.817734,1085.957828
15,gemini/gemini-2.5-flash,screw,160,0.796885,0.884120,4040.841105
16,gemini/gemini-2.5-flash,tile,117,0.786977,0.988095,3945.857379
17,gemini/gemini-2.5-flash,hazelnut,110,0.679286,0.833333,4008.899553
18,gemini/gemini-2.5-flash,grid,78,0.676692,0.973451,3929.244934
19,gemini/gemini-2.5-flash,metal_nut,115,0.639296,0.908163,3933.382661
20,gemini/gemini-2.5-flash,capsule,132,0.613682,0.888889,3997.731006
21,gemini/gemini-2.5-flash,wood,79,0.591667,0.929134,4071.416938
22,gemini/gemini-2.5-flash,transistor,100,0.591667,0.612903,4043.524536
23,gemini/gemini-2.5-flash,pill,167,0.554010,0.918033,3894.512138
24,gemini/gemini-2.5-flash,toothbrush,42,0.550000,0.848485,3984.961829
25,gemini/gemini-2.5-flash,bottle,83,0.542857,0.875000,3923.942175
26,gemini/gemini-2.5-flash,leather,124,0.541610,0.983957,3879.842730
27,gemini/gemini-2.5-flash,zipper,151,0.538997,0.873469,3868.308724
28,gemini/gemini-2.5-flash,cable,150,0.529985,0.758621,4071.382474
29,gemini/gemini-2.5-flash,carpet,117,0.522873,0.971751,3977.927359
30,openrouter/qwen/qwen3-vl-32b-instruct,pill,167,0.481588,0.904290,2125.902615
31,openrouter/qwen/qwen3-vl-32b-instruct,cable,150,0.349325,0.617647,1913.204519
32,openrouter/qwen/qwen3-vl-32b-instruct,transistor,100,0.338750,0.694737,2270.402213
33,openrouter/qwen/qwen3-vl-32b-instruct,hazelnut,110,0.298929,0.972222,2600.207214
34,openrouter/qwen/qwen3-vl-32b-instruct,zipper,151,0.293461,0.648045,1954.025760
35,openrouter/qwen/qwen3-vl-32b-instruct,bottle,83,0.208730,0.925620,1950.250038
36,openrouter/qwen/qwen3-vl-32b-instruct,toothbrush,42,0.152778,0.949153,2282.727627
37,openrouter/qwen/qwen3-vl-32b-instruct,capsule,132,0.149182,0.788889,1916.440170
38,openrouter/qwen/qwen3-vl-32b-instruct,screw,160,0.138041,0.695652,1755.605113
39,openrouter/qwen/qwen3-vl-32b-instruct,metal_nut,115,0.097019,0.937853,2105.686355
40,openrouter/qwen/qwen3-vl-32b-instruct,grid,78,0.054720,0.982456,2138.848941
41,openrouter/qwen/qwen3-vl-32b-instruct,carpet,117,0.050161,0.977273,2121.521069
42,openrouter/qwen/qwen3-vl-32b-instruct,wood,79,0.025000,0.956522,2504.228373
43,openrouter/qwen/qwen3-vl-32b-instruct,tile,117,0.023088,0.923077,1794.119987
44,openrouter/qwen/qwen3-vl-32b-instruct,leather,124,0.012568,0.978022,2397.417289

In [8]:
# ── Cell 8: Summary table ────────────────────────────────────────────────────
import pandas as pd

if all_category_results:
    df = pd.DataFrame(all_category_results)
    print(f'Mean AUROC : {df.auroc.mean():.3f}')
    print(f'Mean F1    : {df.f1.mean():.3f}')
    print(f'Total cost : ${df.cost.sum():.4f}')
    print()
    display(df.sort_values('auroc', ascending=False).reset_index(drop=True))
else:
    print('No results yet — run Cell 7 first.')

Mean AUROC : 0.885
Mean F1    : 0.870
Total cost : $34.9203

      category     auroc        f1    n      cost
0      leather  1.000000  0.994595  124  3.119505
1         wood  0.999123  0.975610   79  2.003880
2       carpet  0.995987  0.972067  117  2.974335
3         tile  0.995310  0.958084  117  2.158815
4         grid  0.993734  0.982456   78  1.993215
5        cable  0.939561  0.857143  150  0.523980
6         pill  0.894299  0.900763  167  2.950395
7     hazelnut  0.890536  0.832117  110  2.796615
8       zipper  0.872768  0.849057  151  3.871230
9   toothbrush  0.872222  0.848485   42  1.083480
10   metal_nut  0.802053  0.816092  115  1.629255
11       screw  0.783460  0.784141  160  4.059990
12  transistor  0.695625  0.589474  100  2.550600
13     capsule  0.653769  0.817734  132  3.205050

In [9]:
# ── Cell 8: Generate report ──────────────────────────────────────────────────
from vlm_anomaly.analysis.report_generator import generate

report = generate(RESULTS_DIR, str(REPO_ROOT / 'REPORT.md'))
print(f'Report written to {report}')

2026-05-24T03:56:24.807550Z [info     ] report.generate.start          [vlm_anomaly.analysis.report_generator] results_dir=/Users/sabareeswarans/Projects_26/VLM-Anomaly/results
/Users/sabareeswarans/Projects_26/VLM-Anomaly/src/vlm_anomaly/analysis/aggregator.py:78: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat(frames, ignore_index=True)
/Users/sabareeswarans/Projects_26/VLM-Anomaly/src/vlm_anomaly/analysis/aggregator.py:78: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat(frames, ignore_index=True)
/Users/sabareeswarans/Projects_26/VLM-Anomaly/src/vlm_anomaly/analysis/aggregator.py:78: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined = pd.concat(frames, ignore_index=True)
2026-05-24T03:56:29.474978Z [info     ] report.generate.done           [vlm_anomaly.analysis.report_generator] plots=/Users/sabareeswarans/Projects_26/VLM-Anomaly/results/plots report=/Users/sabareeswarans/Projects_26/VLM-Anomaly/REPORT.md

Report written to /Users/sabareeswarans/Projects_26/VLM-Anomaly/REPORT.md